/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VLibro.java
 *
 * Created on 16-feb-2011, 18:17:07
 */

package gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import aplicacion.Libro;
import aplicacion.Ejemplar;
import java.util.ArrayList;

/**
 *
 * @author basesdatos
 */
public class vAcolitos extends javax.swing.JDialog {

     private Integer idLibro;
     private java.util.List<Integer> ejemplaresBorrados;
     private VPrincipal padre;
     private aplicacion.FachadaAplicacion fa;
     private Libro libro;

    /** Creates new form VLibro */
    public vAcolitos(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, java.util.List<String> restoCategorias) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        padre=(VPrincipal) parent;
        btnActualizarCategoriasLibro.setEnabled(false);
        btnActualizarEjemplaresLibro.setEnabled(false);
        btnBorrarLibro.setEnabled(false);
        this.idLibro=null;
        this.ejemplaresBorrados = new java.util.ArrayList<Integer>();

        ModeloListaStrings mListaRC=new ModeloListaStrings();
        lstRestoCategorias.setModel(mListaRC);
        mListaRC.setElementos(restoCategorias);
        if (mListaRC.getSize()>0) {
            lstRestoCategorias.setSelectedIndex(0);
            btnDerecha.setEnabled(true);
        } else btnDerecha.setEnabled(false);
        
        btnIzquierda.setEnabled(false);
        btnBorrarEjemplar.setEnabled(false);
    }

    public vAcolitos(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Libro libro, java.util.List<String> categorias, java.util.List<String> restoCategorias) {
        super(parent, modal);
        this.fa=fa;
        this.libro = libro;
        initComponents();
        padre=(VPrincipal) parent;
        idLibro=libro.getIdLibro();
        textoAno.setText(libro.getAno());
        textoEditorial.setText(libro.getEditorial());
        textoIsbn.setText(libro.getIsbn());
        textoPaginas.setText((libro.getPaginas()).toString());
        textoTitulo.setText(libro.getTitulo());
        textoId.setText(idLibro.toString());

        ModeloListaStrings mListaAutores=new ModeloListaStrings();
        lstAutores.setModel(mListaAutores);
        mListaAutores.setElementos(libro.getAutores());
        if (mListaAutores.getSize()>0){
            lstAutores.setSelectedIndex(0);
            btnBorrarAutor.setEnabled(true);
        } else btnBorrarAutor.setEnabled(false);
        
        ModeloListaStrings mListaRC=new ModeloListaStrings();
        lstRestoCategorias.setModel(mListaRC);
        mListaRC.setElementos(restoCategorias);
        if (mListaRC.getSize()>0) {
            lstRestoCategorias.setSelectedIndex(0);
            btnDerecha.setEnabled(true);
        } else btnDerecha.setEnabled(false);
        
        ModeloListaStrings mListaC=new ModeloListaStrings();
        lstCategoriasLibro.setModel(mListaC);
        mListaC.setElementos(categorias);
        if (mListaC.getSize()>0) {
            lstCategoriasLibro.setSelectedIndex(0);
            btnIzquierda.setEnabled(true);
        } else btnIzquierda.setEnabled(false);

        ModeloTablaEjemplares mTEjemplares = new ModeloTablaEjemplares();
        tablaEjemplares.setModel(mTEjemplares);
        mTEjemplares.setFilas(libro.getEjemplares());
        if (mTEjemplares.getRowCount()>0) {
            tablaEjemplares.setRowSelectionInterval(0, 0);
            btnBorrarEjemplar.setEnabled(true);
        } else btnBorrarEjemplar.setEnabled(false);
        this.ejemplaresBorrados = new java.util.ArrayList<Integer>();


       //btnActualizarEjemplaresLibroActionPerformed(null);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Sara Castro
    private void initComponents() {
        textField1 = new JTextField();
        textField2 = new JTextField();
        textField3 = new JTextField();
        textField4 = new JTextField();
        textField5 = new JTextField();
        textField6 = new JTextField();
        label1 = new JLabel();
        textField7 = new JTextField();
        textField8 = new JTextField();
        scrollPane1 = new JScrollPane();
        list1 = new JList();
        label2 = new JLabel();
        scrollPane2 = new JScrollPane();
        textArea1 = new JTextArea();
        button1 = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ac\u00f3litos");
        setResizable(false);
        var contentPane = getContentPane();

        //---- textField1 ----
        textField1.setEditable(false);
        textField1.setText("Alias...");

        //---- textField2 ----
        textField2.setEditable(false);
        textField2.setText("Influencia...");

        //---- textField3 ----
        textField3.setEditable(false);
        textField3.setText("Nombre completo...");

        //---- textField4 ----
        textField4.setEditable(false);
        textField4.setText("Tel\u00e9fono...");

        //---- textField5 ----
        textField5.setEditable(false);
        textField5.setText("Nombre divisi\u00f3n...");

        //---- textField6 ----
        textField6.setEditable(false);
        textField6.setText("Jefe a cargo...");

        //---- label1 ----
        label1.setText("(Imagen del ac\u00f3lito)");

        //---- textField7 ----
        textField7.setEditable(false);
        textField7.setText("Direcci\u00f3n...");

        //---- textField8 ----
        textField8.setEditable(false);
        textField8.setText("Alta divisi\u00f3n...");

        //======== scrollPane1 ========
        {
            scrollPane1.setViewportView(list1);
        }

        //---- label2 ----
        label2.setText("LISTA DE AC\u00d3LITOS");

        //======== scrollPane2 ========
        {

            //---- textArea1 ----
            textArea1.setText("Descripci\u00f3n...");
            textArea1.setFont(new Font("Inter", Font.PLAIN, 13));
            scrollPane2.setViewportView(textArea1);
        }

        //---- button1 ----
        button1.setText("Guardar edici\u00f3n");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                                            .addComponent(textField5, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textField6, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                                            .addComponent(textField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textField4, GroupLayout.PREFERRED_SIZE, 310, GroupLayout.PREFERRED_SIZE)))
                                    .addGap(12, 12, 12))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                            .addComponent(textField7, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(textField8, GroupLayout.PREFERRED_SIZE, 234, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(textField3, GroupLayout.PREFERRED_SIZE, 320, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scrollPane2))
                                    .addGap(10, 10, 10))))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(label1, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField1, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)))
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(scrollPane1, GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                            .addComponent(label2)
                            .addGap(67, 67, 67))))
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addContainerGap(314, Short.MAX_VALUE)
                    .addComponent(button1)
                    .addGap(339, 339, 339))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(label1, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                                .addComponent(textField1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addComponent(textField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(textField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(textField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(textField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(textField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(textField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(textField8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(scrollPane2, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(label2)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(scrollPane1, GroupLayout.PREFERRED_SIZE, 360, GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(button1, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        padre.buscarLibros();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAutorActionPerformed
        // TODO add your handling code here:
     ModeloListaStrings ma;
     ma=(ModeloListaStrings) lstAutores.getModel();

     if ((textoNuevoAutor.getText()!=null) && !(textoNuevoAutor.getText().isEmpty())) {
         ma.nuevoElemento(textoNuevoAutor.getText());
         lstAutores.setSelectedIndex(ma.getSize()-1);
         btnBorrarAutor.setEnabled(true);
     }
    }//GEN-LAST:event_btnNuevoAutorActionPerformed

    private void btnBorrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAutorActionPerformed
        // TODO add your handling code here:
     ModeloListaStrings ma;
     ma=(ModeloListaStrings) lstAutores.getModel();

     ma.borrarElemento(lstAutores.getSelectedIndex());
     if (ma.getSize()==0) btnBorrarAutor.setEnabled(false);
     else lstAutores.setSelectedIndex(0);
    }//GEN-LAST:event_btnBorrarAutorActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        // TODO add your handling code here:
     ModeloListaStrings mRC;
     ModeloListaStrings mC;

     mRC = (ModeloListaStrings) lstRestoCategorias.getModel();
     mC = (ModeloListaStrings) lstCategoriasLibro.getModel();
     mC.nuevoElemento(mRC.getElementAt(lstRestoCategorias.getSelectedIndex()));
     mRC.borrarElemento(lstRestoCategorias.getSelectedIndex());
     if (mRC.getSize()==0) btnDerecha.setEnabled(false);
     else lstRestoCategorias.setSelectedIndex(0);
     lstCategoriasLibro.setSelectedIndex(mC.getSize()-1);
     btnIzquierda.setEnabled(true);
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        // TODO add your handling code here:
     ModeloListaStrings mRC;
     ModeloListaStrings mC;

     mRC = (ModeloListaStrings) lstRestoCategorias.getModel();
     mC = (ModeloListaStrings) lstCategoriasLibro.getModel();
     mRC.nuevoElemento(mC.getElementAt(lstCategoriasLibro.getSelectedIndex()));
     mC.borrarElemento(lstCategoriasLibro.getSelectedIndex());
     if (mC.getSize()==0) btnIzquierda.setEnabled(false);
     else lstCategoriasLibro.setSelectedIndex(0);
     lstRestoCategorias.setSelectedIndex(mRC.getSize()-1);
     btnDerecha.setEnabled(true);
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnBorrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarLibroActionPerformed
        // TODO add your handling code here:
    fa.borrarLibro(idLibro);
    padre.buscarLibros();
    this.dispose();
    }//GEN-LAST:event_btnBorrarLibroActionPerformed

    private void btnActualizarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLibroActionPerformed
        // TODO add your handling code here:
        Libro l;
        l=new Libro(idLibro, textoTitulo.getText(), textoIsbn.getText(), textoEditorial.getText(),
                    Integer.parseInt(textoPaginas.getText()), textoAno.getText());
        ModeloListaStrings ma= (ModeloListaStrings)lstAutores.getModel();
        l.setAutores(ma.getElementos());
        idLibro=fa.actualizarLibro(l);
        textoId.setText(idLibro.toString());
        btnActualizarCategoriasLibro.setEnabled(true);
        btnActualizarEjemplaresLibro.setEnabled(true);
        btnBorrarLibro.setEnabled(true);
    }//GEN-LAST:event_btnActualizarLibroActionPerformed

    private void btnActualizarCategoriasLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCategoriasLibroActionPerformed
        // TODO add your handling code here:
      ModeloListaStrings ma= (ModeloListaStrings)lstCategoriasLibro.getModel();
      fa.actualizarCategoriasLibro(idLibro, ma.getElementos());
    }//GEN-LAST:event_btnActualizarCategoriasLibroActionPerformed

    public void actualizarEjemplares(){
        java.util.List<Ejemplar> ejemplares;
        
        ModeloTablaEjemplares me= (ModeloTablaEjemplares)tablaEjemplares.getModel();
        
        ejemplares=fa.actualizarEjemplaresLibro(idLibro, me.getFilas(), ejemplaresBorrados);
        me.setFilas(ejemplares);
        if (me.getRowCount()>0) {
            tablaEjemplares.setRowSelectionInterval(0, 0);
            btnBorrarEjemplar.setEnabled(true);
        } else btnBorrarEjemplar.setEnabled(false);
    }
    private void btnActualizarEjemplaresLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEjemplaresLibroActionPerformed
        // TODO add your handling code here:
        actualizarEjemplares();
    }//GEN-LAST:event_btnActualizarEjemplaresLibroActionPerformed

    private void btnNuevoEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEjemplarActionPerformed
        // TODO add your handling code here:
        ModeloTablaEjemplares me;
        Ejemplar e;

        me=(ModeloTablaEjemplares) tablaEjemplares.getModel();
        e=new Ejemplar(null, null, null, null,null,null);
        me.nuevoEjemplar(e);
        tablaEjemplares.setRowSelectionInterval(me.getRowCount()-1, me.getRowCount()-1);
        
        btnBorrarEjemplar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoEjemplarActionPerformed

    private void btnPrestarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarEjemplarActionPerformed
       fa.prestar(((ModeloTablaEjemplares)tablaEjemplares.getModel()).obtenerEjemplar(tablaEjemplares.getSelectedRow()));
       actualizarEjemplares();
    }//GEN-LAST:event_btnPrestarEjemplarActionPerformed

    private void btnBorrarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEjemplarActionPerformed
        //fa.borrarEjemplar(idLibro,((ModeloTablaEjemplares)tablaEjemplares.getModel()).obtenerEjemplar(tablaEjemplares.getSelectedRow()).getNumEjemplar());
        ArrayList<Ejemplar> aux = new ArrayList(((ModeloTablaEjemplares)tablaEjemplares.getModel()).getFilas());
        ejemplaresBorrados.add(aux.get(tablaEjemplares.getSelectedRow()).getNumEjemplar());
        aux.remove(tablaEjemplares.getSelectedRow());
        
        ((ModeloTablaEjemplares)tablaEjemplares.getModel()).setFilas(aux);
    }//GEN-LAST:event_btnBorrarEjemplarActionPerformed

    private void btnDevolverEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverEjemplarActionPerformed
        // TODO add your handling code here:
        fa.devolver(((ModeloTablaEjemplares)tablaEjemplares.getModel()).obtenerEjemplar(tablaEjemplares.getSelectedRow()));
        ((ModeloTablaEjemplares)tablaEjemplares.getModel()).setFilas(libro.getEjemplares());
    }//GEN-LAST:event_btnDevolverEjemplarActionPerformed

    private void tablaEjemplaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEjemplaresMouseClicked
        // TODO add your handling code here:
        if (((ModeloTablaEjemplares)tablaEjemplares.getModel()).getFilas().get(tablaEjemplares.getSelectedRow()).getFechaPrestamo() != null)
            btnPrestarEjemplar.setEnabled(false);
        else
            btnPrestarEjemplar.setEnabled(true);
    }//GEN-LAST:event_tablaEjemplaresMouseClicked

      
    
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Sara Castro
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JTextField textField5;
    private JTextField textField6;
    private JLabel label1;
    private JTextField textField7;
    private JTextField textField8;
    private JScrollPane scrollPane1;
    private JList list1;
    private JLabel label2;
    private JScrollPane scrollPane2;
    private JTextArea textArea1;
    private JButton button1;
    // End of variables declaration//GEN-END:variables

}
