/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VLibro.java
 *
 * Created on 16-feb-2011, 18:17:07
 */

package gui;

import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import aplicacion.Libro;
import aplicacion.Ejemplar;
import java.util.ArrayList;

/**
 *
 * @author basesdatos
 */
public class vAcolitos extends javax.swing.JDialog {

     private Integer idLibro;
     private java.util.List<Integer> ejemplaresBorrados;
     private VPrincipal padre;
     private aplicacion.FachadaAplicacion fa;
     private Libro libro;

    /** Creates new form VLibro */
    public vAcolitos(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, java.util.List<String> restoCategorias) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        padre=(VPrincipal) parent;
        btnActualizarCategoriasLibro.setEnabled(false);
        btnActualizarEjemplaresLibro.setEnabled(false);
        btnBorrarLibro.setEnabled(false);
        this.idLibro=null;
        this.ejemplaresBorrados = new java.util.ArrayList<Integer>();

        ModeloListaStrings mListaRC=new ModeloListaStrings();
        lstRestoCategorias.setModel(mListaRC);
        mListaRC.setElementos(restoCategorias);
        if (mListaRC.getSize()>0) {
            lstRestoCategorias.setSelectedIndex(0);
            btnDerecha.setEnabled(true);
        } else btnDerecha.setEnabled(false);
        
        btnIzquierda.setEnabled(false);
        btnBorrarEjemplar.setEnabled(false);
    }

    public vAcolitos(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Libro libro, java.util.List<String> categorias, java.util.List<String> restoCategorias) {
        super(parent, modal);
        this.fa=fa;
        this.libro = libro;
        initComponents();
        padre=(VPrincipal) parent;
        idLibro=libro.getIdLibro();
        textoAno.setText(libro.getAno());
        textoEditorial.setText(libro.getEditorial());
        textoIsbn.setText(libro.getIsbn());
        textoPaginas.setText((libro.getPaginas()).toString());
        textoTitulo.setText(libro.getTitulo());
        textoId.setText(idLibro.toString());

        ModeloListaStrings mListaAutores=new ModeloListaStrings();
        lstAutores.setModel(mListaAutores);
        mListaAutores.setElementos(libro.getAutores());
        if (mListaAutores.getSize()>0){
            lstAutores.setSelectedIndex(0);
            btnBorrarAutor.setEnabled(true);
        } else btnBorrarAutor.setEnabled(false);
        
        ModeloListaStrings mListaRC=new ModeloListaStrings();
        lstRestoCategorias.setModel(mListaRC);
        mListaRC.setElementos(restoCategorias);
        if (mListaRC.getSize()>0) {
            lstRestoCategorias.setSelectedIndex(0);
            btnDerecha.setEnabled(true);
        } else btnDerecha.setEnabled(false);
        
        ModeloListaStrings mListaC=new ModeloListaStrings();
        lstCategoriasLibro.setModel(mListaC);
        mListaC.setElementos(categorias);
        if (mListaC.getSize()>0) {
            lstCategoriasLibro.setSelectedIndex(0);
            btnIzquierda.setEnabled(true);
        } else btnIzquierda.setEnabled(false);

        ModeloTablaEjemplares mTEjemplares = new ModeloTablaEjemplares();
        tablaEjemplares.setModel(mTEjemplares);
        mTEjemplares.setFilas(libro.getEjemplares());
        if (mTEjemplares.getRowCount()>0) {
            tablaEjemplares.setRowSelectionInterval(0, 0);
            btnBorrarEjemplar.setEnabled(true);
        } else btnBorrarEjemplar.setEnabled(false);
        this.ejemplaresBorrados = new java.util.ArrayList<Integer>();


       //btnActualizarEjemplaresLibroActionPerformed(null);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Sara Castro
    private void initComponents() {
        panelLibro = new JTabbedPane();
        panelGeneralAutores = new JPanel();
        jLabel2 = new JLabel();
        textoTitulo = new JTextField();
        jLabel3 = new JLabel();
        textoIsbn = new JTextField();
        jLabel4 = new JLabel();
        textoEditorial = new JTextField();
        jLabel5 = new JLabel();
        textoPaginas = new JTextField();
        jLabel6 = new JLabel();
        textoAno = new JTextField();
        jScrollPane1 = new JScrollPane();
        lstAutores = new JList();
        jLabel7 = new JLabel();
        textoNuevoAutor = new JTextField();
        btnNuevoAutor = new JButton();
        btnBorrarAutor = new JButton();
        btnActualizarLibro = new JButton();
        jLabel1 = new JLabel();
        textoId = new JTextField();
        panelCategorias = new JPanel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jScrollPane2 = new JScrollPane();
        lstRestoCategorias = new JList();
        jScrollPane3 = new JScrollPane();
        lstCategoriasLibro = new JList();
        btnDerecha = new JButton();
        btnIzquierda = new JButton();
        btnActualizarCategoriasLibro = new JButton();
        panelEjemplares = new JPanel();
        jScrollPane4 = new JScrollPane();
        tablaEjemplares = new JTable();
        btnNuevoEjemplar = new JButton();
        btnActualizarEjemplaresLibro = new JButton();
        btnPrestarEjemplar = new JButton();
        btnBorrarEjemplar = new JButton();
        btnDevolverEjemplar = new JButton();
        btnBorrarLibro = new JButton();
        btnSalir = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gesti\u00f3n de libros");
        setResizable(false);
        var contentPane = getContentPane();

        //======== panelLibro ========
        {

            //======== panelGeneralAutores ========
            {
                panelGeneralAutores.setBorder (new javax. swing. border. CompoundBorder( new javax .swing .border .TitledBorder (new javax. swing. border. EmptyBorder( 0
                , 0, 0, 0) , "JFor\u006dDesi\u0067ner \u0045valu\u0061tion", javax. swing. border. TitledBorder. CENTER, javax. swing. border. TitledBorder. BOTTOM
                , new java .awt .Font ("Dia\u006cog" ,java .awt .Font .BOLD ,12 ), java. awt. Color. red) ,
                panelGeneralAutores. getBorder( )) ); panelGeneralAutores. addPropertyChangeListener (new java. beans. PropertyChangeListener( ){ @Override public void propertyChange (java .beans .PropertyChangeEvent e
                ) {if ("bord\u0065r" .equals (e .getPropertyName () )) throw new RuntimeException( ); }} );

                //---- jLabel2 ----
                jLabel2.setText("T\u00edtulo:");

                //---- jLabel3 ----
                jLabel3.setText("Isbn:");

                //---- jLabel4 ----
                jLabel4.setText("Editorial:");

                //---- jLabel5 ----
                jLabel5.setText("P\u00e1ginas:");

                //---- jLabel6 ----
                jLabel6.setText("A\u00f1o:");

                //======== jScrollPane1 ========
                {

                    //---- lstAutores ----
                    lstAutores.setModel(new ModeloListaStrings());
                    lstAutores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                    jScrollPane1.setViewportView(lstAutores);
                }

                //---- jLabel7 ----
                jLabel7.setText("Autores:");

                //---- btnNuevoAutor ----
                btnNuevoAutor.setText("A\u00f1adir");
                btnNuevoAutor.addActionListener(e -> btnNuevoAutorActionPerformed(e));

                //---- btnBorrarAutor ----
                btnBorrarAutor.setText("Borrar");
                btnBorrarAutor.addActionListener(e -> btnBorrarAutorActionPerformed(e));

                //---- btnActualizarLibro ----
                btnActualizarLibro.setText("Actualizar");
                btnActualizarLibro.addActionListener(e -> btnActualizarLibroActionPerformed(e));

                //---- jLabel1 ----
                jLabel1.setText("Id:");

                //---- textoId ----
                textoId.setEditable(false);
                textoId.setEnabled(false);

                GroupLayout panelGeneralAutoresLayout = new GroupLayout(panelGeneralAutores);
                panelGeneralAutores.setLayout(panelGeneralAutoresLayout);
                panelGeneralAutoresLayout.setHorizontalGroup(
                    panelGeneralAutoresLayout.createParallelGroup()
                        .addGroup(panelGeneralAutoresLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelGeneralAutoresLayout.createParallelGroup()
                                .addGroup(panelGeneralAutoresLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textoTitulo, GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                                .addGroup(panelGeneralAutoresLayout.createSequentialGroup()
                                    .addGroup(panelGeneralAutoresLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(GroupLayout.Alignment.LEADING, panelGeneralAutoresLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textoIsbn, GroupLayout.PREFERRED_SIZE, 152, GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel4))
                                        .addGroup(GroupLayout.Alignment.LEADING, panelGeneralAutoresLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(textoPaginas, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(textoAno)))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelGeneralAutoresLayout.createParallelGroup()
                                        .addComponent(textoEditorial, GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                        .addGroup(panelGeneralAutoresLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textoId, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 140, Short.MAX_VALUE))))
                                .addComponent(jLabel7)
                                .addGroup(panelGeneralAutoresLayout.createSequentialGroup()
                                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelGeneralAutoresLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBorrarAutor, GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.LEADING, panelGeneralAutoresLayout.createSequentialGroup()
                                            .addComponent(btnNuevoAutor)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(textoNuevoAutor, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                                        .addComponent(btnActualizarLibro))))
                            .addContainerGap())
                );
                panelGeneralAutoresLayout.setVerticalGroup(
                    panelGeneralAutoresLayout.createParallelGroup()
                        .addGroup(panelGeneralAutoresLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelGeneralAutoresLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(textoTitulo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(panelGeneralAutoresLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(textoIsbn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(textoEditorial, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelGeneralAutoresLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(textoPaginas, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(textoAno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(textoId, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addComponent(jLabel7)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelGeneralAutoresLayout.createParallelGroup()
                                .addGroup(panelGeneralAutoresLayout.createSequentialGroup()
                                    .addGroup(panelGeneralAutoresLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnNuevoAutor)
                                        .addComponent(textoNuevoAutor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBorrarAutor)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnActualizarLibro))
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                            .addContainerGap())
                );
            }
            panelLibro.addTab("Libro", panelGeneralAutores);

            //======== panelCategorias ========
            {

                //---- jLabel8 ----
                jLabel8.setText("Categor\u00edas disponibles");

                //---- jLabel9 ----
                jLabel9.setText("Categor\u00edas del libro");

                //======== jScrollPane2 ========
                {

                    //---- lstRestoCategorias ----
                    lstRestoCategorias.setModel(new ModeloListaStrings());
                    jScrollPane2.setViewportView(lstRestoCategorias);
                }

                //======== jScrollPane3 ========
                {

                    //---- lstCategoriasLibro ----
                    lstCategoriasLibro.setModel(new ModeloListaStrings());
                    jScrollPane3.setViewportView(lstCategoriasLibro);
                }

                //---- btnDerecha ----
                btnDerecha.setIcon(new ImageIcon(getClass().getResource("/gui/flechaD.jpg")));
                btnDerecha.addActionListener(e -> btnDerechaActionPerformed(e));

                //---- btnIzquierda ----
                btnIzquierda.setIcon(new ImageIcon(getClass().getResource("/gui/flechaI.jpg")));
                btnIzquierda.addActionListener(e -> btnIzquierdaActionPerformed(e));

                //---- btnActualizarCategoriasLibro ----
                btnActualizarCategoriasLibro.setText("Actualizar");
                btnActualizarCategoriasLibro.addActionListener(e -> btnActualizarCategoriasLibroActionPerformed(e));

                GroupLayout panelCategoriasLayout = new GroupLayout(panelCategorias);
                panelCategorias.setLayout(panelCategoriasLayout);
                panelCategoriasLayout.setHorizontalGroup(
                    panelCategoriasLayout.createParallelGroup()
                        .addGroup(panelCategoriasLayout.createSequentialGroup()
                            .addGroup(panelCategoriasLayout.createParallelGroup()
                                .addGroup(panelCategoriasLayout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(jLabel8))
                                .addGroup(panelCategoriasLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelCategoriasLayout.createParallelGroup()
                                .addGroup(panelCategoriasLayout.createSequentialGroup()
                                    .addGroup(panelCategoriasLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnDerecha, 0, 0, Short.MAX_VALUE)
                                        .addComponent(btnIzquierda, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(GroupLayout.Alignment.TRAILING, panelCategoriasLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(65, 65, 65))))
                        .addGroup(GroupLayout.Alignment.TRAILING, panelCategoriasLayout.createSequentialGroup()
                            .addContainerGap(397, Short.MAX_VALUE)
                            .addComponent(btnActualizarCategoriasLibro)
                            .addContainerGap())
                );
                panelCategoriasLayout.setVerticalGroup(
                    panelCategoriasLayout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, panelCategoriasLayout.createSequentialGroup()
                            .addGroup(panelCategoriasLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addGroup(GroupLayout.Alignment.LEADING, panelCategoriasLayout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(btnDerecha, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnIzquierda, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
                                .addGroup(GroupLayout.Alignment.LEADING, panelCategoriasLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(panelCategoriasLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelCategoriasLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizarCategoriasLibro)
                            .addContainerGap())
                );
            }
            panelLibro.addTab("Categor\u00edas", panelCategorias);

            //======== panelEjemplares ========
            {

                //======== jScrollPane4 ========
                {

                    //---- tablaEjemplares ----
                    tablaEjemplares.setModel(new ModeloTablaEjemplares());
                    tablaEjemplares.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            tablaEjemplaresMouseClicked(e);
                        }
                    });
                    jScrollPane4.setViewportView(tablaEjemplares);
                }

                //---- btnNuevoEjemplar ----
                btnNuevoEjemplar.setText("Nuevo");
                btnNuevoEjemplar.addActionListener(e -> btnNuevoEjemplarActionPerformed(e));

                //---- btnActualizarEjemplaresLibro ----
                btnActualizarEjemplaresLibro.setText("Actualizar");
                btnActualizarEjemplaresLibro.addActionListener(e -> btnActualizarEjemplaresLibroActionPerformed(e));

                //---- btnPrestarEjemplar ----
                btnPrestarEjemplar.setText("Prestar");
                btnPrestarEjemplar.addActionListener(e -> btnPrestarEjemplarActionPerformed(e));

                //---- btnBorrarEjemplar ----
                btnBorrarEjemplar.setText("Borrar");
                btnBorrarEjemplar.addActionListener(e -> btnBorrarEjemplarActionPerformed(e));

                //---- btnDevolverEjemplar ----
                btnDevolverEjemplar.setText("Devolver");
                btnDevolverEjemplar.addActionListener(e -> btnDevolverEjemplarActionPerformed(e));

                GroupLayout panelEjemplaresLayout = new GroupLayout(panelEjemplares);
                panelEjemplares.setLayout(panelEjemplaresLayout);
                panelEjemplaresLayout.setHorizontalGroup(
                    panelEjemplaresLayout.createParallelGroup()
                        .addComponent(jScrollPane4, GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                        .addGroup(panelEjemplaresLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnNuevoEjemplar)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBorrarEjemplar)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPrestarEjemplar)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDevolverEjemplar, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizarEjemplaresLibro)
                            .addGap(24, 24, 24))
                );
                panelEjemplaresLayout.setVerticalGroup(
                    panelEjemplaresLayout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, panelEjemplaresLayout.createSequentialGroup()
                            .addComponent(jScrollPane4, GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelEjemplaresLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNuevoEjemplar)
                                .addComponent(btnActualizarEjemplaresLibro)
                                .addComponent(btnPrestarEjemplar)
                                .addComponent(btnBorrarEjemplar)
                                .addComponent(btnDevolverEjemplar))
                            .addContainerGap())
                );
            }
            panelLibro.addTab("Ejemplares", panelEjemplares);
        }

        //---- btnBorrarLibro ----
        btnBorrarLibro.setText("Borrar Libro");
        btnBorrarLibro.addActionListener(e -> btnBorrarLibroActionPerformed(e));

        //---- btnSalir ----
        btnSalir.setText("Sal\u00edr");
        btnSalir.addActionListener(e -> btnSalirActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnBorrarLibro)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                    .addComponent(btnSalir)
                    .addContainerGap())
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(panelLibro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(panelLibro, GroupLayout.PREFERRED_SIZE, 371, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(btnBorrarLibro)
                        .addComponent(btnSalir))
                    .addContainerGap(13, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        padre.buscarLibros();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAutorActionPerformed
        // TODO add your handling code here:
     ModeloListaStrings ma;
     ma=(ModeloListaStrings) lstAutores.getModel();

     if ((textoNuevoAutor.getText()!=null) && !(textoNuevoAutor.getText().isEmpty())) {
         ma.nuevoElemento(textoNuevoAutor.getText());
         lstAutores.setSelectedIndex(ma.getSize()-1);
         btnBorrarAutor.setEnabled(true);
     }
    }//GEN-LAST:event_btnNuevoAutorActionPerformed

    private void btnBorrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAutorActionPerformed
        // TODO add your handling code here:
     ModeloListaStrings ma;
     ma=(ModeloListaStrings) lstAutores.getModel();

     ma.borrarElemento(lstAutores.getSelectedIndex());
     if (ma.getSize()==0) btnBorrarAutor.setEnabled(false);
     else lstAutores.setSelectedIndex(0);
    }//GEN-LAST:event_btnBorrarAutorActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        // TODO add your handling code here:
     ModeloListaStrings mRC;
     ModeloListaStrings mC;

     mRC = (ModeloListaStrings) lstRestoCategorias.getModel();
     mC = (ModeloListaStrings) lstCategoriasLibro.getModel();
     mC.nuevoElemento(mRC.getElementAt(lstRestoCategorias.getSelectedIndex()));
     mRC.borrarElemento(lstRestoCategorias.getSelectedIndex());
     if (mRC.getSize()==0) btnDerecha.setEnabled(false);
     else lstRestoCategorias.setSelectedIndex(0);
     lstCategoriasLibro.setSelectedIndex(mC.getSize()-1);
     btnIzquierda.setEnabled(true);
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        // TODO add your handling code here:
     ModeloListaStrings mRC;
     ModeloListaStrings mC;

     mRC = (ModeloListaStrings) lstRestoCategorias.getModel();
     mC = (ModeloListaStrings) lstCategoriasLibro.getModel();
     mRC.nuevoElemento(mC.getElementAt(lstCategoriasLibro.getSelectedIndex()));
     mC.borrarElemento(lstCategoriasLibro.getSelectedIndex());
     if (mC.getSize()==0) btnIzquierda.setEnabled(false);
     else lstCategoriasLibro.setSelectedIndex(0);
     lstRestoCategorias.setSelectedIndex(mRC.getSize()-1);
     btnDerecha.setEnabled(true);
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnBorrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarLibroActionPerformed
        // TODO add your handling code here:
    fa.borrarLibro(idLibro);
    padre.buscarLibros();
    this.dispose();
    }//GEN-LAST:event_btnBorrarLibroActionPerformed

    private void btnActualizarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLibroActionPerformed
        // TODO add your handling code here:
        Libro l;
        l=new Libro(idLibro, textoTitulo.getText(), textoIsbn.getText(), textoEditorial.getText(),
                    Integer.parseInt(textoPaginas.getText()), textoAno.getText());
        ModeloListaStrings ma= (ModeloListaStrings)lstAutores.getModel();
        l.setAutores(ma.getElementos());
        idLibro=fa.actualizarLibro(l);
        textoId.setText(idLibro.toString());
        btnActualizarCategoriasLibro.setEnabled(true);
        btnActualizarEjemplaresLibro.setEnabled(true);
        btnBorrarLibro.setEnabled(true);
    }//GEN-LAST:event_btnActualizarLibroActionPerformed

    private void btnActualizarCategoriasLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCategoriasLibroActionPerformed
        // TODO add your handling code here:
      ModeloListaStrings ma= (ModeloListaStrings)lstCategoriasLibro.getModel();
      fa.actualizarCategoriasLibro(idLibro, ma.getElementos());
    }//GEN-LAST:event_btnActualizarCategoriasLibroActionPerformed

    public void actualizarEjemplares(){
        java.util.List<Ejemplar> ejemplares;
        
        ModeloTablaEjemplares me= (ModeloTablaEjemplares)tablaEjemplares.getModel();
        
        ejemplares=fa.actualizarEjemplaresLibro(idLibro, me.getFilas(), ejemplaresBorrados);
        me.setFilas(ejemplares);
        if (me.getRowCount()>0) {
            tablaEjemplares.setRowSelectionInterval(0, 0);
            btnBorrarEjemplar.setEnabled(true);
        } else btnBorrarEjemplar.setEnabled(false);
    }
    private void btnActualizarEjemplaresLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEjemplaresLibroActionPerformed
        // TODO add your handling code here:
        actualizarEjemplares();
    }//GEN-LAST:event_btnActualizarEjemplaresLibroActionPerformed

    private void btnNuevoEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEjemplarActionPerformed
        // TODO add your handling code here:
        ModeloTablaEjemplares me;
        Ejemplar e;

        me=(ModeloTablaEjemplares) tablaEjemplares.getModel();
        e=new Ejemplar(null, null, null, null,null,null);
        me.nuevoEjemplar(e);
        tablaEjemplares.setRowSelectionInterval(me.getRowCount()-1, me.getRowCount()-1);
        
        btnBorrarEjemplar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoEjemplarActionPerformed

    private void btnPrestarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarEjemplarActionPerformed
       fa.prestar(((ModeloTablaEjemplares)tablaEjemplares.getModel()).obtenerEjemplar(tablaEjemplares.getSelectedRow()));
       actualizarEjemplares();
    }//GEN-LAST:event_btnPrestarEjemplarActionPerformed

    private void btnBorrarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEjemplarActionPerformed
        //fa.borrarEjemplar(idLibro,((ModeloTablaEjemplares)tablaEjemplares.getModel()).obtenerEjemplar(tablaEjemplares.getSelectedRow()).getNumEjemplar());
        ArrayList<Ejemplar> aux = new ArrayList(((ModeloTablaEjemplares)tablaEjemplares.getModel()).getFilas());
        ejemplaresBorrados.add(aux.get(tablaEjemplares.getSelectedRow()).getNumEjemplar());
        aux.remove(tablaEjemplares.getSelectedRow());
        
        ((ModeloTablaEjemplares)tablaEjemplares.getModel()).setFilas(aux);
    }//GEN-LAST:event_btnBorrarEjemplarActionPerformed

    private void btnDevolverEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverEjemplarActionPerformed
        // TODO add your handling code here:
        fa.devolver(((ModeloTablaEjemplares)tablaEjemplares.getModel()).obtenerEjemplar(tablaEjemplares.getSelectedRow()));
        ((ModeloTablaEjemplares)tablaEjemplares.getModel()).setFilas(libro.getEjemplares());
    }//GEN-LAST:event_btnDevolverEjemplarActionPerformed

    private void tablaEjemplaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEjemplaresMouseClicked
        // TODO add your handling code here:
        if (((ModeloTablaEjemplares)tablaEjemplares.getModel()).getFilas().get(tablaEjemplares.getSelectedRow()).getFechaPrestamo() != null)
            btnPrestarEjemplar.setEnabled(false);
        else
            btnPrestarEjemplar.setEnabled(true);
    }//GEN-LAST:event_tablaEjemplaresMouseClicked

      
    
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Sara Castro
    private JTabbedPane panelLibro;
    private JPanel panelGeneralAutores;
    private JLabel jLabel2;
    private JTextField textoTitulo;
    private JLabel jLabel3;
    private JTextField textoIsbn;
    private JLabel jLabel4;
    private JTextField textoEditorial;
    private JLabel jLabel5;
    private JTextField textoPaginas;
    private JLabel jLabel6;
    private JTextField textoAno;
    private JScrollPane jScrollPane1;
    private JList lstAutores;
    private JLabel jLabel7;
    private JTextField textoNuevoAutor;
    private JButton btnNuevoAutor;
    private JButton btnBorrarAutor;
    private JButton btnActualizarLibro;
    private JLabel jLabel1;
    private JTextField textoId;
    private JPanel panelCategorias;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane2;
    private JList lstRestoCategorias;
    private JScrollPane jScrollPane3;
    private JList lstCategoriasLibro;
    private JButton btnDerecha;
    private JButton btnIzquierda;
    private JButton btnActualizarCategoriasLibro;
    private JPanel panelEjemplares;
    private JScrollPane jScrollPane4;
    private JTable tablaEjemplares;
    private JButton btnNuevoEjemplar;
    private JButton btnActualizarEjemplaresLibro;
    private JButton btnPrestarEjemplar;
    private JButton btnBorrarEjemplar;
    private JButton btnDevolverEjemplar;
    private JButton btnBorrarLibro;
    private JButton btnSalir;
    // End of variables declaration//GEN-END:variables

}
