/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VUsuarios.java
 *
 * Created on 16-feb-2011, 18:17:07
 */

package gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

import aplicacion.Evento;

/**
 *
 * @author basesdatos
 */
public class VPrestar extends javax.swing.JDialog {

     protected VLibro padre;
     private aplicacion.FachadaAplicacion fa;
     private Evento evento;

    /** Creates new form VLibro */
    public VPrestar(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Evento evento) {
        super(parent, modal);
        this.fa=fa;
        this.evento = evento;
        initComponents();
        //((ModeloPrestamos)jTable1.getModel()).setFilas(fa.obtenerUsuariosPretamos());
        ((ModeloPrestamos)jTable1.getModel()).setFilas(fa.buscarUsuariosPrestamos(jTextFieldIDUsuarioBusqueda.getText(),jTextFieldNombreUsuarioBusqueda.getText()));
        jLabel3.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Mateo Bodenlle Villarino
    private void initComponents() {
        btnPrestarLibro = new JButton();
        btnSalir = new JButton();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jLabel1 = new JLabel();
        jTextFieldIDUsuarioBusqueda = new JTextField();
        jTextFieldNombreUsuarioBusqueda = new JTextField();
        jLabel2 = new JLabel();
        btnBuscar = new JButton();
        jLabel3 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gesti\u00f3n de libros");
        setResizable(false);
        var contentPane = getContentPane();

        //---- btnPrestarLibro ----
        btnPrestarLibro.setFont(new Font("sansserif", Font.BOLD, 14));
        btnPrestarLibro.setText("Prestar");
        btnPrestarLibro.addActionListener(e -> btnPrestarLibroActionPerformed(e));

        //---- btnSalir ----
        btnSalir.setText("Salir");
        btnSalir.addActionListener(e -> btnSalirActionPerformed(e));

        //======== jScrollPane1 ========
        {

            //---- jTable1 ----
            jTable1.setModel(new ModeloPrestamos()
            );
            jTable1.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    jTable1MouseClicked(e);
                }
            });
            jScrollPane1.setViewportView(jTable1);
        }

        //---- jLabel1 ----
        jLabel1.setText("ID");

        //---- jLabel2 ----
        jLabel2.setText("Name");

        //---- btnBuscar ----
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(e -> btnBuscarActionPerformed(e));

        //---- jLabel3 ----
        jLabel3.setFont(new Font("sansserif", Font.PLAIN, 12));
        jLabel3.setForeground(Color.red);
        jLabel3.setText("No se puede prestar a usuarios con pr\u00e9stamos vencidos");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, GroupLayout.Alignment.LEADING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 368, GroupLayout.PREFERRED_SIZE))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldIDUsuarioBusqueda, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombreUsuarioBusqueda, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)))
                    .addGap(12, 12, 12))
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap(225, Short.MAX_VALUE)
                    .addComponent(btnPrestarLibro, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                    .addGap(156, 156, 156)
                    .addComponent(btnSalir, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldIDUsuarioBusqueda, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldNombreUsuarioBusqueda, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addGap(15, 15, 15)
                    .addComponent(jLabel3)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 217, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(btnSalir, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(btnPrestarLibro, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        //re.buscarLibros();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPrestarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarLibroActionPerformed
        if (!jTable1.getModel().getValueAt(jTable1.getSelectedRow(),3).equals(0))
            jLabel3.setVisible(true);
        else{
            jLabel3.setVisible(false);
            fa.anadirPrestamo(((ModeloPrestamos)jTable1.getModel()).getUsuario(jTable1.getSelectedRow()), evento);
            this.dispose();
        }

    }//GEN-LAST:event_btnPrestarLibroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        ((ModeloPrestamos)jTable1.getModel()).setFilas(fa.buscarUsuariosPrestamos(jTextFieldIDUsuarioBusqueda.getText(),jTextFieldNombreUsuarioBusqueda.getText()));

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jLabel3.setVisible(false);
    }//GEN-LAST:event_jTable1MouseClicked

      
   
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Mateo Bodenlle Villarino
    private JButton btnPrestarLibro;
    private JButton btnSalir;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    private JLabel jLabel1;
    private JTextField jTextFieldIDUsuarioBusqueda;
    private JTextField jTextFieldNombreUsuarioBusqueda;
    private JLabel jLabel2;
    private JButton btnBuscar;
    private JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
