/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VUsuarios.java
 *
 * Created on 16-feb-2011, 18:17:07
 */

package gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

import aplicacion.Acolito;
import aplicacion.TipoAcolito;
import aplicacion.TipoUsuario;
import aplicacion.Usuario;

/**
 *
 * @author basesdatos
 */
public class VUsuarios extends javax.swing.JDialog {

     private VPrincipal padre;
     private aplicacion.FachadaAplicacion fa;

    /** Creates new form VLibro */
    public VUsuarios(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        ((ModeloUsuarios)jTable1.getModel()).setFilas(fa.consultarAcolitos());
        
        jComboBox1.addItem(" ");
        for (TipoUsuario i: TipoUsuario.values())
            jComboBox1.addItem(i.toString());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.categoria
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Laura Antelo González
    private void initComponents() {
        btnBorrarLibro = new JButton();
        btnSalir = new JButton();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        btnBorrarLibro1 = new JButton();
        btnBorrarLibro2 = new JButton();
        jTextField1 = new JTextField();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jTextField2 = new JTextField();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jTextField3 = new JTextField();
        jTextField4 = new JTextField();
        jLabel5 = new JLabel();
        jTextField5 = new JTextField();
        jLabel6 = new JLabel();
        jComboBox1 = new JComboBox<>();
        jLabel7 = new JLabel();
        jTextFieldIDBusqueda = new JTextField();
        jTextFieldNombreBusqueda = new JTextField();
        jLabel8 = new JLabel();
        btnBuscar = new JButton();
        jLabel9 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gesti\u00f3n de usuarios");
        setResizable(false);
        var contentPane = getContentPane();

        //---- btnBorrarLibro ----
        btnBorrarLibro.setText("Nuevo");
        btnBorrarLibro.setToolTipText("");
        btnBorrarLibro.addActionListener(e -> btnNuevoActionPerformed(e));

        //---- btnSalir ----
        btnSalir.setText("Salir");
        btnSalir.addActionListener(e -> btnSalirActionPerformed(e));

        //======== jScrollPane1 ========
        {

            //---- jTable1 ----
            jTable1.setModel(new ModeloUsuarios());
            jTable1.setPreferredSize(new Dimension(500, 80));
            jTable1.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    jTable1MouseClicked(e);
                }
            });
            jScrollPane1.setViewportView(jTable1);
        }

        //---- btnBorrarLibro1 ----
        btnBorrarLibro1.setText("Guardar");
        btnBorrarLibro1.addActionListener(e -> btnGuardarActionPerformed(e));

        //---- btnBorrarLibro2 ----
        btnBorrarLibro2.setText("Borrar");
        btnBorrarLibro2.addActionListener(e -> btnBorrarActionPerformed(e));

        //---- jTextField1 ----
        jTextField1.setHorizontalAlignment(SwingConstants.LEFT);
        jTextField1.addActionListener(e -> jTextField1ActionPerformed(e));

        //---- jLabel1 ----
        jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel1.setText("Nombre");

        //---- jLabel2 ----
        jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel2.setText("ID");

        //---- jTextField2 ----
        jTextField2.setHorizontalAlignment(SwingConstants.LEFT);
        jTextField2.addActionListener(e -> jTextField2ActionPerformed(e));

        //---- jLabel3 ----
        jLabel3.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel3.setText("Clave");

        //---- jLabel4 ----
        jLabel4.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel4.setText("direcci\u00f3n");

        //---- jTextField3 ----
        jTextField3.setHorizontalAlignment(SwingConstants.LEFT);
        jTextField3.addActionListener(e -> jTextField3ActionPerformed(e));

        //---- jTextField4 ----
        jTextField4.setHorizontalAlignment(SwingConstants.LEFT);
        jTextField4.addActionListener(e -> jTextField4ActionPerformed(e));

        //---- jLabel5 ----
        jLabel5.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel5.setText("email");

        //---- jTextField5 ----
        jTextField5.setHorizontalAlignment(SwingConstants.LEFT);
        jTextField5.addActionListener(e -> jTextField5ActionPerformed(e));

        //---- jLabel6 ----
        jLabel6.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel6.setText("Tipo");

        //---- jComboBox1 ----
        jComboBox1.addActionListener(e -> jComboBox1ActionPerformed(e));

        //---- jLabel7 ----
        jLabel7.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel7.setText("ID");

        //---- jTextFieldIDBusqueda ----
        jTextFieldIDBusqueda.addActionListener(e -> jTextFieldIDBusquedaActionPerformed(e));

        //---- jTextFieldNombreBusqueda ----
        jTextFieldNombreBusqueda.addActionListener(e -> jTextFieldNombreBusquedaActionPerformed(e));

        //---- jLabel8 ----
        jLabel8.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel8.setText("Nombre");

        //---- btnBuscar ----
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(e -> btnBuscarActionPerformed(e));

        //---- jLabel9 ----
        jLabel9.setFont(new Font("sansserif", Font.PLAIN, 14));
        jLabel9.setForeground(new Color(0xff0033));
        jLabel9.setText("No puedes repetir IdUsuario");
                jLabel9.setVisible(false);

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGroup(contentPaneLayout.createParallelGroup()
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(jLabel2))
                                        .addComponent(jLabel1, GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                        .addComponent(jTextField2))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE))
                                    .addGap(16, 16, 16))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addComponent(btnBorrarLibro, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBorrarLibro1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField3, GroupLayout.Alignment.LEADING)
                                .addComponent(btnBorrarLibro2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(jTextField4))
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(contentPaneLayout.createParallelGroup()
                                        .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(contentPaneLayout.createParallelGroup()
                                        .addComponent(jTextField5)
                                        .addComponent(jComboBox1))
                                    .addGap(12, 12, 12))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(btnSalir, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldIDBusqueda, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombreBusqueda, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1))
                            .addGap(12, 12, 12))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(257, 257, 257)
                            .addComponent(jLabel9)
                            .addGap(0, 0, Short.MAX_VALUE))))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIDBusqueda, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldNombreBusqueda, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(btnBuscar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 265, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel5))))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBorrarLibro)
                        .addComponent(btnBorrarLibro2)
                        .addComponent(btnBorrarLibro1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addContainerGap())
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        //re.buscarLibros();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        jTextField2.setText("");
        jTextField1.setText("");
        jTextField4.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedItem(" ");
        ((ModeloUsuarios)jTable1.getModel()).setFilas(fa.consultarAcolitos());
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //Comprobación de si existe en la bd
        ModeloUsuarios mu = (ModeloUsuarios)jTable1.getModel();
        Acolito u = new Acolito(jTextField2.getText(),jTextField4.getText(),jTextField1.getText(),jTextField3.getText(),0, TipoAcolito.stringToTipoAcolito(jComboBox1.getSelectedItem().toString()));
        Acolito us;


        if (jTable1.getSelectedRow()!=-1){ //Borramos el usuario anterior al editar..
            us = mu.obtenerUsuario(jTable1.getSelectedRow()); //Usuario seleccionado
            for (Acolito iu: fa.consultarAcolitos())
                if (iu.getAliasAcolito().equals(u.getAliasAcolito()) && !iu.getAliasAcolito().equals(us.getAliasAcolito())){
                    jLabel9.setVisible(true);
                    return;
                }
            fa.borrarUsuario(us);
        }
        for (Acolito iu: fa.consultarAcolitos())
            if (iu.getAliasAcolito().equals(u.getAliasAcolito())){
                jLabel9.setVisible(true);
                return;
            }
        fa.nuevoUsuario(u); //Si estamos creando un usuario en vez de editar, no se borra el usuario anterior

        ((ModeloUsuarios)jTable1.getModel()).setFilas(fa.consultarAcolitos());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        ModeloUsuarios mu = (ModeloUsuarios)jTable1.getModel();
        Usuario u = mu.obtenerUsuario(jTable1.getSelectedRow());

        fa.borrarUsuario(u);
        ((ModeloUsuarios)jTable1.getModel()).setFilas(fa.consultarAcolitos()); //Refrescar la tabla

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextFieldIDBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDBusquedaActionPerformed

    private void jTextFieldNombreBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreBusquedaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        ((ModeloUsuarios)jTable1.getModel()).setFilas(fa.consultarAcolitos(jTextFieldIDBusqueda.getText(),jTextFieldNombreBusqueda.getText()));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (jTable1.getSelectedRow()!=-1){
        jTextField2.setText(((ModeloUsuarios)jTable1.getModel()).obtenerUsuario(jTable1.getSelectedRow()).getAlias());
        jTextField1.setText(((ModeloUsuarios)jTable1.getModel()).obtenerUsuario(jTable1.getSelectedRow()).getNombreCompleto());
        jTextField4.setText(((ModeloUsuarios)jTable1.getModel()).obtenerUsuario(jTable1.getSelectedRow()).getContraseña());
        jTextField3.setText(((ModeloUsuarios)jTable1.getModel()).obtenerUsuario(jTable1.getSelectedRow()).getDireccion());
        jTextField5.setText(((ModeloUsuarios)jTable1.getModel()).obtenerUsuario(jTable1.getSelectedRow()).getEmail());

        jComboBox1.setSelectedItem(((ModeloUsuarios)jTable1.getModel()).obtenerUsuario(jTable1.getSelectedRow()).getTipoAcolito().toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

      
   
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Laura Antelo González
    private JButton btnBorrarLibro;
    private JButton btnSalir;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    private JButton btnBorrarLibro1;
    private JButton btnBorrarLibro2;
    private JTextField jTextField1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JTextField jTextField2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JLabel jLabel5;
    private JTextField jTextField5;
    private JLabel jLabel6;
    private JComboBox<String> jComboBox1;
    private JLabel jLabel7;
    private JTextField jTextFieldIDBusqueda;
    private JTextField jTextFieldNombreBusqueda;
    private JLabel jLabel8;
    private JButton btnBuscar;
    private JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
